<h1>Stock Prediction</h1>
<p>The goal here is to find an algorithm that will capture buying, sell and hold signals. There are xxx steps taken:</p>
<ol>
    <li>Get ETF with the following information: "open", "high", "low", "close", "volume"</li>
    <br>
    <li>Calculate all the following information:
        <br><b>Volume</b>
        <br>
        <br>Accumulation/Distribution Index (ADI)
        <br>On-Balance Volume (OBV)
        <br>Chaikin Money Flow (CMF)
        <br>Force Index (FI)
        <br>Ease of Movement (EoM, EMV)
        <br>Volume-price Trend (VPT)
        <br>Negative Volume Index (NVI)
        <br>
        <br>
        <br><b>Volatility</b>
        <br>
        <br>Average True Range (ATR)
        <br>Bollinger Bands (BB)
        <br>Keltner Channel (KC)
        <br>Donchian Channel (DC)
        <br>
        <br><b>Trend</b>
        <br>
        <br>Moving Average Convergence Divergence (MACD)
        <br>Average Directional Movement Index (ADX)
        <br>Vortex Indicator (VI)
        <br>Trix (TRIX)
        <br>Mass Index (MI)
        <br>Commodity Channel Index (CCI)
        <br>Detrended Price Oscillator (DPO)
        <br>KST Oscillator (KST)
        <br>Ichimoku Kinkō Hyō (Ichimoku)
        <br>
        <br><b>Momentum</b>
        <br>
        <br>Money Flow Index (MFI)
        <br>Relative Strength Index (RSI)
        <br>True strength index (TSI)
        <br>Ultimate Oscillator (UO)
        <br>Stochastic Oscillator (SR)
        <br>Williams %R (WR)
        <br>Awesome Oscillator (AO)
        <br>
        <br><b>Others</b>
        <br>
        <br>Daily Return (DR)
        <br>Daily Log Return (DLR)
        <br>Cumulative Return (CR)</li>
        <br>
        <br>
    <li>We normalize each column using normal normalization</li>
    <br>
    <li> We perform a PCA in each one of the Drivers (OriginalData, Volume,Volatility, Trend, Momentum and Others) and get the number of columns needed to explain, at least 85% in each one of the Drivers (This percentage can be changed, it is a hyperparameter).  </li>
    <br>
    <li>Make the Following Predictions:</li>
        <ul>
            <li>Next day up over 0.3%, lower than -0.3% or between</li>
        </ul>

    

</ol>

In [38]:
#!pip install ta
import ta
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from TransformData import Normalizer, PCA_, GetTA



pipe = Pipeline([('etf_ta',GetTA()),('normalizing',Normalizer()),('pca',PCA_(0.9))])

qqq = pd.read_csv('AlphaVantageDaily_adjusted_qqq.csv', infer_datetime_format=True,  index_col=['timestamp'])
print(qqq.head(3))
print('##########')

qqq_t = pipe.fit_transform(qqq)

print(qqq_t.shape)

print(qqq_t.columns)

print(qqq_t.head())

              open    high     low   close  adjusted_close    volume  \
timestamp                                                              
2019-06-27  186.47  186.94  185.99  186.72          186.72  15889915   
2019-06-26  186.13  187.33  185.49  185.79          185.79  22512628   
2019-06-25  188.06  188.14  184.65  184.93          184.93  33921112   

            dividend_amount  split_coefficient  
timestamp                                       
2019-06-27              0.0                1.0  
2019-06-26              0.0                1.0  
2019-06-25              0.0                1.0  
##########


C:\Users\vinic\Anaconda3\lib\site-packages\ta\trend.py:170: RuntimeWarning: divide by zero encountered in double_scalars
  dip[i] = 100 * (dip_mio[i]/trs[i])
C:\Users\vinic\Anaconda3\lib\site-packages\ta\trend.py:170: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (dip_mio[i]/trs[i])
C:\Users\vinic\Anaconda3\lib\site-packages\ta\trend.py:174: RuntimeWarning: divide by zero encountered in double_scalars
  din[i] = 100 * (din_mio[i]/trs[i])
C:\Users\vinic\Anaconda3\lib\site-packages\ta\trend.py:174: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (din_mio[i]/trs[i])
C:\Users\vinic\Anaconda3\lib\site-packages\ta\trend.py:176: RuntimeWarning: invalid value encountered in subtract
  dx = 100 * np.abs((dip - din) / (dip + din))


(5109, 25)
Index(['OriginalData_0', 'OriginalData_1', 'Volume_0', 'Volume_1', 'Volume_2',
       'Volume_3', 'Volume_4', 'Volume_5', 'Volatility_0', 'Volatility_1',
       'Volatility_2', 'Volatility_3', 'Volatility_4', 'Trend_0', 'Trend_1',
       'Trend_2', 'Trend_3', 'Trend_4', 'Trend_5', 'Trend_6', 'Momentum_0',
       'Momentum_1', 'Momentum_2', 'Others_0', 'Others_1'],
      dtype='object')
            OriginalData_0  OriginalData_1  Volume_0  Volume_1  Volume_2  \
timestamp                                                                  
2019-06-27        0.041568       -0.008132  0.049774  0.003139 -0.003051   
2019-06-26        0.041063       -0.008043  0.077261 -0.004463  0.004619   
2019-06-25        0.040478       -0.007935  0.024791 -0.003373  0.000905   
2019-06-24        0.081197        0.226276  0.026368 -0.004845  0.006705   
2019-06-21        0.041027       -0.008018  0.024165 -0.007306  0.011767   

            Volume_3  Volume_4  Volume_5  Volatility_0  Volatility_

<h1>Predictions</h1>
<br>
<p>Let's make the first prediction, if the etf is going to go up over 0.3%, below 0.3% or maintain betweet one week from now </p>

In [2]:
import keras



Using TensorFlow backend.


In [3]:
print(qqq.index[0])
print(qqq.index[-1])
print(qqq_t.index[0])
print(qqq_t.index[-1])

2019-06-27
1999-03-10
2019-06-27
1999-03-10


In [39]:
# Creating the Y vector.

num = qqq.iloc[0:-5]['adjusted_close']
den = qqq.iloc[5:]['adjusted_close']


Y = [ x/y - 1 for x,y in zip(num,den)]
print(max(Y))
print(min(Y))

for i in range(len(Y)):
    if Y[i] > 0.03:
        Y[i] = 0
    
    elif Y[i] < -0.03:
        Y[i] = 2
        
    else:
        Y[i] = 1


0.20720259205744562
-0.24596608509596452


In [41]:
# Adjusting the X data to have the same length as Y. The dates also should have one week difference.
print(qqq.index[0])
X = qqq_t.iloc[5:]
print(X.index[0])

print(X.shape)
print(len(Y))

2019-06-27
2019-06-20
(5104, 25)
5104


{1: 3593, 0: 788, 2: 723}


In [42]:
lookback= 50
def create_dataset(df,lookback):
    finalDf = []
    print(lookback)
    print(df.shape[0])
    for i in range(lookback, df.shape[0]):

        finalDf.append(np.array(df.iloc[i-lookback:i]))
    finalDf = np.array(finalDf)
    return finalDf

X = X.reset_index(drop = True)

X = create_dataset(X, lookback)
Y = Y[:-50]

Y = np.array(Y).reshape(len(Y),1)


print(X.shape)
print(Y.shape)

50
5104
(5054, 50, 25)
(5054, 1)


In [44]:
# Dealing with unbalanced data

def count_(list_):
    dict_ = {}
    for i in range(len(list_)):
        
        if list_[i] in dict_.keys():
            dict_[list_[i]] = dict_[list_[i]] + 1
            
        else:
            dict_[list_[i]] = 1
    return dict_

print(count_(Y.reshape(-1)))


{1: 3562, 0: 787, 2: 705}


In [60]:
# # Setting a Validation Data aside. This will be done because We'll duplicate the low frequency data. 
# validation_size = int(0.1*len(Y))

# # selecting indexes for validation
# indexes = np.random.choice(len(Y), validation_size, replace = False)
# y_validation = []
# y = []

# for i in range(len(Y)):
#     if i in indexes:
#         y_validation.append(Y[i])
        
#     else:
#         y.append(Y[i])
        
# print(len(indexes))
# print(len(y_validation))
# print(len(y))

# # Now let's get the X with the same indexes. 
# print(X.shape)
# X_validation = X[1:3,:,:]
# print(X.shape)
# print(X_validation.shape)

505
505
4549
(5054, 50, 25)
(5054, 50, 25)
(2, 50, 25)


In [46]:
from keras.utils import to_categorical
from keras import Sequential
from keras.layers import Dense, LSTM
from sklearn.model_selection import KFold

seed = 42

kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
cvscores = []


for train, test in kfold.split(X, Y):
    # create model

    model = Sequential()
    model.add(LSTM(units=70, return_sequences= True, input_shape=(lookback,25)))
    model.add(LSTM(units=40, return_sequences=True))
    model.add(LSTM(units=30, return_sequences=True))
    model.add(LSTM(units=10))
    model.add(Dense(units=3, activation='sigmoid'))
    
    y_b_train = Y[train]
    y_b_test = Y[test]
    
    X_train = X[train]
    X_test = X[test]
    
    
    y_train_binary = to_categorical(y_b_train)
    y_test_binary = to_categorical(y_b_test)
    
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
    
    model.fit(X_train, y_train_binary, epochs=4, batch_size=128)

    scores = model.evaluate(X_test,y_test_binary, verbose=1)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
    cvscores.append(scores[1] * 100)
    
    
    
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))


Epoch 1/4
4548/4548 [==============================] - 23s 5ms/step - loss: 0.9563 - acc: 0.6838
Epoch 2/4
4548/4548 [==============================] - 18s 4ms/step - loss: 0.8399 - acc: 0.6953
Epoch 3/4
4548/4548 [==============================] - 19s 4ms/step - loss: 0.8259 - acc: 0.6953
Epoch 4/4
506/506 [==============================] - 6s 12ms/step
acc: 79.05%
Epoch 1/4
4548/4548 [==============================] - 24s 5ms/step - loss: 0.9322 - acc: 0.6783
Epoch 2/4
4548/4548 [==============================] - 19s 4ms/step - loss: 0.8382 - acc: 0.6873
Epoch 3/4
4548/4548 [==============================] - 20s 4ms/step - loss: 0.8380 - acc: 0.6873
Epoch 4/4
506/506 [==============================] - 6s 12ms/step
acc: 86.17%
Epoch 1/4
4548/4548 [==============================] - 24s 5ms/step - loss: 0.9295 - acc: 0.6755
Epoch 2/4
4548/4548 [==============================] - 19s 4ms/step - loss: 0.8422 - acc: 0.6847
Epoch 3/4
4548/4548 [==============================] - 19s 4ms/step 

array([ 506,  507,  508, ..., 5051, 5052, 5053])

In [96]:
# print(Y_pred[0])

# test = [[round(x[0]), round(x[1]), round(x[2])] for x in Y_pred]

# from sklearn.metrics import confusion_matrix

# def get_confusion_matrix(Y, Y_pred):
    
#     y = []
#     y_pred = []
    
#     for i in range(Y.shape[0]):
#         if Y[i][0] >0:
#             y.append('buy')
        
#         elif Y[i][1] >0:
#             y.append('hold')
        
#         else:
#             y.append('sell')
            
    
#     for i in range(Y_pred.shape[0]):
#         if Y_pred[i][0] >0:
#             y_pred.append('buy')
        
#         elif Y_pred[i][1] >0:
#             y_pred.append('hold')
        
#         else:
#             y_pred.append('sell')
        
    
#     return y, y_pred

# Y, y_pred = get_confusion_matrix(y_binary,Y_pred)


# print(confusion_matrix(Y, y_pred))
# print(temp[0])
# print(y_binary[0])

[3.9030515e-04 9.8091495e-01 1.0628104e-03]
[[   0    0    0]
 [5049    0    0]
 [   5    0    0]]
hold
[0. 1. 0.]


In [143]:
# temp = X.reset_index(drop = True)

In [146]:
# temp.loc[test].head()

OriginalData_0  OriginalData_1  Volume_0  Volume_1  Volume_2  Volume_3  \
26        0.039052       -0.007701  0.008007  0.002738 -0.008013  0.000283   
38        0.042133       -0.008209  0.005843  0.019749 -0.022744 -0.001013   
42        0.042705       -0.008313 -0.001122  0.006269 -0.003901 -0.004907   
44        0.042193       -0.008221 -0.005459  0.005599  0.000247 -0.006957   
45        0.042252       -0.008236 -0.000062  0.002961  0.002409 -0.005756   

    Volume_4  Volume_5  Volatility_0  Volatility_1  ...   Trend_2   Trend_3  \
26  0.005950 -0.013782      0.046802      0.007247  ... -0.001135 -0.010623   
38 -0.001172 -0.013445      0.036927      0.073391  ...  0.017024 -0.032375   
42  0.004775 -0.010391      0.050601      0.007871  ...  0.013694 -0.033869   
44  0.006305 -0.007910      0.050761      0.007799  ...  0.008040 -0.039490   
45  0.011697 -0.005217      0.050659      0.007706  ...  0.011961 -0.037750   

     Trend_4   Trend_5   Trend_6  Momentum_0  Momentum_1  Momentum_2  \
26  0.042895 -0.042629  0.062107    0.041504    0.048005   -0.027294   
38  0.032682 -0.013867  0.029739    0.053535    0.030563   -0.019515   
42  0.028497 -0.007240  0.025442    0.055001    0.027472   -0.013972   
44  0.024184 -0.000716  0.024071    0.053673    0.027048   -0.013310   
45  0.019704  0.001172  0.015005    0.051826    0.027958   -0.011900   

    Others_0  Others_1  
26  0.003648 -0.000360  
38  0.005015 -0.000596  
42  0.006341 -0.000876  
44 -0.000676  0.000612  
45 -0.003226  0.001157  

[5 rows x 25 columns]